### ISSUE TITLE
URL no longer links to RSS-feed

### ISSUE THREAD

**Issue by stevewhitmore** [sdepold/jquery-rss#74]
I noticed the RSS feed I have set up on a website I'm working on for my firm no longer displays RSS content. I was doing jQuery updates on the site so I reverted it to an older version (+1 week old when feed was still showing up) to see if I was causing a conflict but the issue remained. I tried setting up the feed in a different environment but keep getting the "jQuery RSS: url doesn't link to RSS-Feed" error message. I've also tried using different feeds from different sites but run into the same issue. 

Do you know what could have changed in the last 48 hours that would cause this? I've got it set up in a test environment [here](http://dev.swhitmore.com/rss-test/). The .rss() function gets called in script.js and I put a few print statements inside jquery.rss.js to try and debug the issue but I'm not having much luck. 

Any help would be greatly appreciated!

**Comment by sdepold** [comment]
Hi @stevewhitmore,

did which version of jqueryrss are you running? Is it possible that you didn't update in a while and still run a version < 3.0 ? If that's the case, you experience the shutdown of the google feed api which is deprecated since the beginning of the year. Please upgrade jquery.rss to use the sort-of drop-in replacement that I wrote and which is used by jquery-rss 3.0+. Please note that you can also host the server on your own: https://github.com/sdepold/feedrapp

**Comment by stevewhitmore** [comment]
Thanks for your quick reply @sdepold. I think we're good to go now. I appreciate the help!
